TOPDIR := ${shell pwd | sed -e 's/ /\\ /g'}/../../../../nuttx
include ${TOPDIR}/.config
include ${TOPDIR}/tools/Config.mk
include ${TOPDIR}/arch/arm/src/armv7-m/Toolchain.defs

smxengine.o: smxengine.cpp
